"""empty message

Revision ID: cf69336ddc83
Revises: 0f56ec6dea69
Create Date: 2023-01-11 20:08:08.002708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf69336ddc83'
down_revision = '0f56ec6dea69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidateDB', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('candidateDB', 'password',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('candidateDB', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('candidateDB', 'first_surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('candidateDB', 'second_surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidateDB', 'second_surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('candidateDB', 'first_surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('candidateDB', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('candidateDB', 'password',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('candidateDB', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
