"""empty message

Revision ID: e0fd41fa6ae8
Revises: 
Create Date: 2023-01-10 18:55:48.422529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fd41fa6ae8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidateDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('first_surname', sa.String(length=50), nullable=True),
    sa.Column('second_surname', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_offerDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruitee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('requirements', sa.String(length=500), nullable=False),
    sa.Column('postal_code', sa.String(length=5), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('state_code', sa.String(length=3), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruiterDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('first_surname', sa.String(length=50), nullable=True),
    sa.Column('second_surname', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recruiterDB')
    op.drop_table('job_offerDB')
    op.drop_table('candidateDB')
    # ### end Alembic commands ###
